StableSwapperAsAService/StableSwapperAsAService/urls.py
# Django
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

# 3rd Party
import debug_toolbar

# fmt: off
urlpatterns = [

    path('admin/', admin.site.urls, name="admin"),
    
    path('', RedirectView.as_view(pattern_name='bots:home'), name='landing-page'),
    path('bot/', include('bot.urls')),
    path('statistics/', include('statistics.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
        ]

# fmt: on

StableSwapperAsAService/bot/urls.py

# Django
from django.urls import path

# Local
from bot import views
from bot.views import actions as action_views

app_name = 'bots'

# fmt: off
urlpatterns = [
    # Website
    path('', views.HomeView.as_view(), name='home'),
    path('details/<str:wallet_address>/', views.DetailsView.as_view(), name="details"),
    path('checks/<str:wallet_address>/', views.ChecksView.as_view(), name='checks-list'),
    path('transactions/<str:wallet_address>/', views.TransactionsView.as_view(), name='transactions-list'),

    # Actions
    path('action/trigger-swap/', action_views.SwapTriggerView.as_view()),
    path('action/manage-checks-runner/', action_views.ManageChecksRunnerTriggerView.as_view()),
    path('action/delete-old-checks/', action_views.OldChecksDeleteTriggerView.as_view()),
    path('action/confirm-transactions/', action_views.ConfirmTransactionTriggerView.as_view()),
    path('action/warn-about-errors/', action_views.WarnAboutErrorsView.as_view()),
    path('action/update-settings/', action_views.UpdateSettingsTriggerView.as_view()),
] 
# fmt: on

StableSwapperAsAService/bot/models/check.py
# Django
from django.db import models
from django.utils import timezone

# Local
from kernel.models import Token
from kernel.models import Transaction
from kernel.models import Wallet


class Check(models.Model):
    date = models.DateTimeField(default=timezone.now)
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE)
    duration_seconds = models.FloatField(blank=True, null=True)
    total_owned = models.FloatField(blank=True, null=True)
    token_to_swap_from = models.ForeignKey(Token, on_delete=models.CASCADE, related_name='check_from', null=True)
    amount_to_swap_from = models.FloatField(blank=True, null=True)
    token_to_swap_to = models.ForeignKey(Token, on_delete=models.CASCADE, related_name='check_to', null=True)
    amount_to_swap_to = models.FloatField(blank=True, null=True)
    forecasted_profit = models.FloatField(blank=True, null=True)
    aborted = models.BooleanField(blank=True, null=True)
    transaction = models.OneToOneField(Transaction, on_delete=models.CASCADE, null=True, blank=True, related_name="bot_check")
    raw_data = models.TextField(blank=True, default='')
    
    error = models.TextField(blank=True, null=True, default='')
    failed = models.BooleanField(default=False)

    def __str__(self):
        return "[id: %s, date: %s, aborted: %s]" % (self.id, self.date, self.aborted)

StableSwapperAsAService/bot/models/checks_runner_session.py
# Python
from datetime import timedelta

# Django
from django.db import models
from django.utils import timezone

# Local
from kernel.models import Wallet


class ChecksRunnerSession(models.Model):
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE, editable=False)
    start_date = models.DateTimeField(default=timezone.now)
    shutdown_date = models.DateTimeField(blank=True, null=True, default=None)
    last_check_date = models.DateTimeField(blank=True, null=True, default=None)
    check_batches_triggered = models.IntegerField(default=0)
    should_shutdown = models.BooleanField(default=False)
    error = models.TextField(blank=True)
    ran_until_completion = models.BooleanField(default=False)

    @property
    def duration_in_seconds(self):
        if not self.shutdown_date:
            return -1
        return (self.shutdown_date - self.start_date).total_seconds()

    @property
    def is_runner_idle(self):
        date = self.last_check_date or self.start_date
        two_mins_ago = timezone.now() - timedelta(seconds=60)
        return date < two_mins_ago

StableSwapperAsAService/bot/views/checks_view.py
# Django
from django.views.generic import ListView

# Local
from bot.models import Check


class ChecksView(ListView):
    template_name = 'bot/page-checks.html'
    model = Check
    context_object_name = 'checks'
    queryset = Check.objects.all().select_related('token_to_swap_from', 'token_to_swap_to').order_by('-date')
    paginate_by = 120

    def get_queryset(self):        
        wallet_address = self.kwargs.get('wallet_address', None)
        return super().get_queryset().filter(wallet__address=wallet_address)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['wallet_address'] = self.kwargs.get('wallet_address', None)
        return context

StableSwapperAsAService/bot/views/details_view.py
# Local
import math
from typing import Dict, Any
from datetime import timedelta

# Django
from django.utils import timezone
from django.views.generic.base import TemplateView
from django.shortcuts import get_object_or_404

# Local
from blockchainProxy.wallet_checker import WalletChecker
from kernel.models import Transaction
from kernel.models import Wallet
from bot.models import Check
from sharedSettings.models import SharedSettings
from statistics.helpers.profit_and_interests import ProfitAndInterests


class DetailsView(TemplateView):
    template_name = 'bot/page-details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        wallet_address = self.kwargs.get('wallet_address', None)
        wallet = get_object_or_404(Wallet, address=wallet_address)
        
        context.update(DetailsView.get_statistics(wallet))

        context['wallet_address'] = wallet.address
        context['latest_transactions'] = Transaction.objects.filter(wallet=wallet).select_related('token_from', 'token_to').order_by('-date')[:20]
        context['nr_transactions'] = Transaction.objects.filter(wallet=wallet).count()

        context['latest_checks'] = Check.objects.filter(wallet=wallet).select_related('token_to_swap_from', 'token_to_swap_to').order_by('-date')[:19]
        context['nr_checks'] = Check.objects.filter(wallet=wallet).count()
        context['MINIMUM_SWAPPABLE'] = float(SharedSettings.get('MINIMUM_SWAPPABLE'))

        return context

    @staticmethod
    def get_statistics(wallet: Wallet) -> Dict[str, Any]:
        context = {}

        context['owned_tokens'] = sorted(
            WalletChecker.get_tokens_amounts(wallet.address), key=lambda tk: tk.adjusted_amount, reverse=True
        )
        context['owned_tokens'].insert(0, WalletChecker.get_matic_balance(wallet.address))

        last_week = timezone.now() - timedelta(days=7) 
        txs = Transaction.objects.filter(date__gte=last_week, wallet__address=wallet.address, state=Transaction.States.CONFIRMED)
        profits_and_interests = ProfitAndInterests(txs, wallet)

        context['total_owned'] = profits_and_interests.total_owned
        context['initial'] = profits_and_interests.initially_owned
        context['initial_date'] = profits_and_interests.initial_date
        context['profit_abs'] = profits_and_interests.total_profit
        context['profit_perc'] = profits_and_interests.profit_percentage
        context['daily_APR'] = profits_and_interests.daily_APR
        context['APR'] = profits_and_interests.APR
        context['APY'] = profits_and_interests.APY
        
        return context

StableSwapperAsAService/bot/views/home_view.py

# Python
from typing import Dict, Any, Tuple, List, Optional
from datetime import timedelta
import json
import logging
import concurrent.futures

# Django
from django.conf import settings
from django.utils import timezone
from django.views.generic import TemplateView
from django.core import serializers
from django.forms.models import model_to_dict

# 3rd Party
import requests

# Local
from kernel.models import Wallet
from statistics.models import WalletDailyStatistic

logger = logging.getLogger(__name__)


class WalletWithInfo:
    def __init__(self, wallet_address: str, stats: Optional[WalletDailyStatistic]):
        self.wallet = wallet_address
        self.stats = stats

    def to_dict(self):
        return {"wallet" : self.wallet, "stats": model_to_dict(self.stats) if self.stats else None }

class HomeView(TemplateView):
    template_name = 'bot/page-home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['instance_name'] = settings.INSTANCE_NAME
        context['wallets_with_stats'] = HomeView.get_wallets_with_statistics()
        context['total_earned_today'] = self._get_total_earned(context['wallets_with_stats'])
        context['total_owned'] = self._get_total_owned(context['wallets_with_stats'])
        return context

    @staticmethod
    def get_wallets_with_statistics() -> List[WalletWithInfo]:
        all_wallets = Wallet.objects.all().values_list('address', flat=True)
        yesterday = (timezone.now() - timedelta(days=1)).date()
        all_stats = WalletDailyStatistic.objects.filter(date__gte=yesterday).select_related('wallet')

        # Keep the latest statistics for each wallet
        stats_per_address: Dict[str, WalletDailyStatistic] = {}
        for stat in all_stats:
            if stat.wallet.address not in stats_per_address or stats_per_address[stat.wallet.address].date < stat.date:
                stats_per_address[stat.wallet.address] = stat

        # As there might be wallets without stats, compare with the full list and create the WalletWithInfo objects
        wallets_with_stats: Tuple[WalletWithInfo] = []
        for wallet_address in all_wallets:
            wallet_stats = stats_per_address.get(wallet_address, None)
            wallets_with_stats.append(WalletWithInfo(wallet_address, wallet_stats))

        return wallets_with_stats

    def _get_total_earned(self, all_wallets: Dict[str, Any]) -> float:
        return sum([wallet.stats.total_delta_profit_in_transactions if wallet.stats else 0 for wallet in all_wallets])
        
    def _get_total_owned(self, all_wallets: Dict[str, Any]) -> float:
        return sum([wallet.stats.total_owned if wallet.stats else 0 for wallet in all_wallets])       

StableSwapperAsAService/bot/views/transactions_view.py
# Django
from django.views.generic import ListView

# Local
from kernel.models import Transaction


class TransactionsView(ListView):
    template_name = 'bot/page-transactions.html'
    model = Transaction
    context_object_name = 'transactions'
    queryset = Transaction.objects.all().select_related('token_from', 'token_to').order_by('-date')
    paginate_by = 120
    
    def get_queryset(self):        
        wallet_address = self.kwargs.get('wallet_address', None)
        return super().get_queryset().filter(wallet__address=wallet_address)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['wallet_address'] = self.kwargs.get('wallet_address', None)
        return context

StableSwapperAsAService/bot/templates/bot/layout.html
{% load static %}
{% load tz %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="{% static 'bot/images/favicon.png' %}" sizes="32x32">
        
    <title>Swapper Bot - {% block title %}{% endblock %}</title>    

    {% block styles %}
        <link rel="stylesheet" type="text/css" href="{% static 'bot/content/shared/fonts.css' %}" />        
        <link rel="stylesheet" type="text/css" href="{% static 'bot/content/shared/shared.css' %}" />        
        <link rel="stylesheet" type="text/css" href="{% static 'bot/content/shared/menu.css' %}" />        
    {% endblock %}
</head>

<body>
   
    <div class="container body-content">
        {% timezone "Europe/Amsterdam" %}

            {% include 'bot/fragments/menu.html' %}

            {% block content %}
            {% endblock %}
        
        {% endtimezone %}
    </div>

    {% block scripts %}    
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>                
    {% endblock %}

</body>
</html>

StableSwapperAsAService/bot/templates/bot/old-page-statistics.html
{% extends "bot/layout.html" %}
{% load static %}

{% block title %}Statistics{% endblock %}

{% block styles %}
{{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'bot/content/page-statistics/pg-statistics-styles.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bot/content/page-statistics/minimal-journal-entry-styles.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bot/content/page-statistics/common-check-errors-styles.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bot/content/page-statistics/network-stats-styles.css' %}" />
{% endblock %}

{% block content %}

    <div class="main-container">

        <!-- Daily Statistics -->
        <div class="statistics-page__section">
            <div class="statistics-page__section-title">Daily Statistics</div>
            <div class="statistics-page__section-panels">
                {% include 'bot/panels-statistics/daily-stats/panel-latest-journal-entries.html' %}
                {% include 'bot/panels-statistics/daily-stats/panel-chart-daily-profit.html' %}
                {% include 'bot/panels-statistics/daily-stats/panel-chart-apy-trend.html' %}
                {% include 'bot/panels-statistics/daily-stats/panel-chart-checks-trend.html' %}
                {% include 'bot/panels-statistics/daily-stats/panel-chart-check-durations.html' %}
                {% include 'bot/panels-statistics/daily-stats/panel-chart-transactions-trend.html' %}
                {% include 'bot/panels-statistics/daily-stats/panel-chart-transactions-pos-vs-neg-count.html' %}
                {% include 'bot/panels-statistics/daily-stats/panel-chart-transactions-pos-vs-neg-amount.html' %}
                {% include 'bot/panels-statistics/daily-stats/panel-chart-transactions-successful-vs-not.html' %}
                {% include 'bot/panels-statistics/daily-stats/panel-chart-daily-fees.html' %}
            </div>
        </div>

        <!-- Transaction Statistics -->
        <div class="statistics-page__section">
            <div class="statistics-page__section-title">Transaction Statistics</div>
            <div class="statistics-page__section-panels">
                {% include 'bot/panels-statistics/tx-stats/panel-network-stats.html' %} 
                {% include 'bot/panels-statistics/tx-stats/panel-chart-delays.html' %} 
                {% include 'bot/panels-statistics/tx-stats/panel-chart-gas-price.html' %} 
                {% include 'bot/panels-statistics/tx-stats/panel-chart-slippage.html' %} 
            </div>
        </div>

        {% comment %}
        <!-- Check Statistics -->
        <div class="statistics-page__section">
            <div class="statistics-page__section-title">Check Statistics</div>
            <div class="statistics-page__section-panels">
                {% include 'bot/panels-statistics/check-stats/panel-chart-deltas.html' %} 
                {% include 'bot/panels-statistics/check-stats/panel-checks-common-errors.html' %} 
                {% include 'bot/panels-statistics/check-stats/panel-chart-tokens-from.html' %} 
                {% include 'bot/panels-statistics/check-stats/panel-chart-tokens-to.html' %} 
                {% include 'bot/panels-statistics/check-stats/panel-chart-failures.html' %} 
            </div>
        </div>
        {% endcomment %}
    
    </div>

{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.3.2/dist/chart.min.js"></script>
    
    <!-- Daily Statistics -->
    <script async src="{% static 'bot/scripts/page-statistics/daily-stats/daily_profit_chart_plotter.js' %}"></script>
    <script async src="{% static 'bot/scripts/page-statistics/daily-stats/daily_apr_chart_plotter.js' %}"></script>
    <script async src="{% static 'bot/scripts/page-statistics/daily-stats/checks_duration_chart_plotter.js' %}"></script>
    <script async src="{% static 'bot/scripts/page-statistics/daily-stats/checks_trend_chart_plotter.js' %}"></script>
    <script async src="{% static 'bot/scripts/page-statistics/daily-stats/transactions_trend_chart_plotter.js' %}"></script>
    <script async src="{% static 'bot/scripts/page-statistics/daily-stats/transactions_pos_vs_neg_count_chart_plotter.js' %}"></script>
    <script async src="{% static 'bot/scripts/page-statistics/daily-stats/transactions_pos_vs_neg_amount_chart_plotter.js' %}"></script>
    <script async src="{% static 'bot/scripts/page-statistics/daily-stats/transactions_successful_vs_not_chart_plotter.js' %}"></script>
    <script async src="{% static 'bot/scripts/page-statistics/daily-stats/daily_fees_chart_plotter.js' %}"></script>
    
    <!-- Transaction Statistics -->
    <script async src="{% static 'bot/scripts/page-statistics/tx-stats/delays_chart_plotter.js' %}"></script>
    <script async src="{% static 'bot/scripts/page-statistics/tx-stats/gas_price_chart_plotter.js' %}"></script>
    <script async src="{% static 'bot/scripts/page-statistics/tx-stats/slippage_chart_plotter.js' %}"></script>
    

    {% comment %}
    <!-- Check Statistics -->
    <script async src="{% static 'bot/scripts/page-statistics/check-stats/delta_chart_plotter.js' %}"></script> 
    <script async src="{% static 'bot/scripts/page-statistics/check-stats/failures_chart_plotter.js' %}"></script> 
    <script async src="{% static 'bot/scripts/page-statistics/check-stats/token_from_chart_plotter.js' %}"></script> 
    <script async src="{% static 'bot/scripts/page-statistics/check-stats/token_to_chart_plotter.js' %}"></script> 
    {% endcomment %}

{% endblock %}

StableSwapperAsAService/bot/templates/bot/page-checks.html
{% extends "bot/layout.html" %}
{% load static %}

{% block title %}Checks{% endblock %}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'bot/content/page-checks/full-check-styles.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bot/content/page-checks/pg-check-styles.css' %}" />
{% endblock %}

{% block content %}

<div class="main-container">

    <div class="checks-container">

        <!-- header -->
        <div class="details-panel__title">All Checks</div>
        <a class="details-panel__link" href="{% url 'bots:details' wallet_address %}">Back to dashboard</a>

        <!-- Checks -->
        {% for ck in checks %}
            {% include 'bot/fragments/full-check.html' %}
        {% endfor %}

        <!-- Pagination -->
        <div class="pagination">
            <div class="pagination__links">
                {% if page_obj.has_previous %}
                    <a class="pagination__arrow-link" href="{% url 'bots:checks-list' wallet_address %}?page={{ page_obj.previous_page_number }}">
                        <div class="pagination__navigation-button pagination__navigation-button--previous"></div>
                    </a>
                {% endif %}
                    <span class="pagination__current-page-text">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                {% if page_obj.has_next %}
                    <a class="pagination__arrow-link" href="{% url 'bots:checks-list' wallet_address %}?page={{ page_obj.next_page_number }}">
                        <div class="pagination__navigation-button pagination__navigation-button--next"></div>
                    </a>
                {% endif %}
            </div>
        </div>

    </div>

</div>

{% endblock %}

StableSwapperAsAService/bot/templates/bot/page-details.html
{% extends "bot/layout.html" %}
{% load static %}

{% block title %}{{total_owned|floatformat:2}}{% endblock %}

{% block styles %}
{{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'bot/content/page-details/pg-details-styles.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bot/content/page-details/minimal-check-styles.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bot/content/page-details/minimal-transaction-styles.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bot/content/page-details/token-styles.css' %}" />
{% endblock %}

{% block content %}

    <div class="main-container">
        
        <input id="id-wallet-address" type="hidden" value="{{wallet_address}}"/>
        {% include 'bot/panels-details/panel-owned-amount.html' %}
        {% include 'bot/panels-details/panel-profits.html' %}
        {% include 'bot/panels-details/panel-aprs.html' %}
        {% include 'bot/panels-details/panel-wallet.html' %}
        {% include 'bot/panels-details/panel-transactions.html' %}
        {% include 'bot/panels-details/panel-checks.html' %}
        {% include 'bot/panels-details/panel-chart-amount.html' %}

    </div>

{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.3.2/dist/chart.min.js"></script>

    <script async src="{% static 'bot/scripts/page-details/amount_chart_plotter.js' %}"></script>
    <script async src="{% static 'bot/scripts/page-details/reloader.js' %}"></script>
{% endblock %}

StableSwapperAsAService/bot/templates/bot/page-home.html
{% extends "bot/layout.html" %}
{% load static %}

{% block title %}{{ instance_name }}{% endblock %}

{% block styles %}
{{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'bot/content/page-home/pg-home-styles.css' %}" />
{% endblock %}

{% block content %}

    <div class="main-container">
        <div class="page-home">
            
            <div class="page-home__left-container">

                <!-- Logo + title -->
                <div class="page-home__header"> 
                    <div class="page-home__title-container"> 
                        <img class="page-home__logo" src="{% static 'bot/images/logo.png' %}"/>
                        <div class="page-home__title">Stable Swapper Bot</div>
                    </div>
                    <div class="page-home__subtitle page-home__subtitle--with-margin">{{ instance_name }}</div>
                    <div class="page-home__text">Get a passive income. Low risk, no hassle.</div>                    
                </div>

                <!-- Stats + Admin buttons -->
                <div class="page-home__links">
                    <a class="page-home__link" href="/statistics/">Statistics</a>
                    {% if user.is_authenticated and user.is_staff %}
                        <a class="page-home__link" href="/admin/">Admin</a>
                    {% endif %}
                </div>
            </div>

            <!-- Wallets list -->
            <div class="page-home__right-container">
                <!-- Wallets in this instance -->
                <div class="page-home__wallets-list">
                    <div class="page-home__subtitle page-home__subtitle--with-margin" style="margin-bottom:0">Managed Wallets</div>
                    <div class="page-home__text page-home__subtitle--with-margin" style="margin-top:0">(Updated every 10 minutes)</div>

                    {% for wallet_with_stats in wallets_with_stats %}
                    <a href="/bot/details/{{ wallet_with_stats.wallet }}/" class="page-home__wallet-with-profit">
                        <div class="page-home__wallet">
                            {{ wallet_with_stats.wallet|truncatechars:25 }}
                        </div>
                        <div class="page-home__wallet-owned">
                            {{ wallet_with_stats.stats.total_owned|floatformat:2 }}$
                        </div>
                        <div class="page-home__wallet-profit">
                            {% if wallet_with_stats.stats.total_delta_profit_in_transactions > 0 %}+{% endif %}{{ wallet_with_stats.stats.total_delta_profit_in_transactions|floatformat:2 }}$
                        </div>
                    </a>
                    {% endfor %}

                </div>

                <!-- Total owned -->
                <div class="page-home__total-earned-contained">
                    <div class="page-home__text">Total owned:</div>
                    <div class="page-home__subtitle" style="margin-left: 10px">{{ total_owned|floatformat:2 }}$</div>
                </div>
                <!-- Total earned today -->
                <div class="page-home__total-earned-contained" style="margin-top: 0">
                    <div class="page-home__text">Total earned today:</div>
                    <div class="page-home__subtitle" style="margin-left: 10px">{{ total_earned_today|floatformat:2 }}$</div>
                </div>

            </div>

        </div>
    </div>

{% endblock %}

StableSwapperAsAService/bot/templates/bot/page-transactions.html
{% extends "bot/layout.html" %}
{% load static %}

{% block title %}Transactions{% endblock %}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'bot/content/page-transactions/full-transaction-styles.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bot/content/page-transactions/pg-transactions-styles.css' %}" />
{% endblock %}

{% block content %}

<div class="main-container">

    <div class="transactions-container">

        <!-- header -->
        <div class="details-panel__title">All Transactions</div>
        <a class="details-panel__link" href="{% url 'bots:details' wallet_address %}">Back to dashboard</a>

        <!-- Checks -->
        {% for tx in transactions %}
            {% include 'bot/fragments/full-transaction.html' %}
        {% endfor %}

        <!-- Pagination -->
        <div class="pagination">
            <div class="pagination__links">
                {% if page_obj.has_previous %}
                    <a class="pagination__arrow-link" href="{% url 'bots:transactions-list' wallet_address %}?page={{ page_obj.previous_page_number }}">
                        <div class="pagination__navigation-button pagination__navigation-button--previous"></div>
                    </a>
                {% endif %}
                    <span class="pagination__current-page-text">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                {% if page_obj.has_next %}
                    <a class="pagination__arrow-link" href="{% url 'bots:transactions-list' wallet_address %}?page={{ page_obj.next_page_number }}">
                        <div class="pagination__navigation-button pagination__navigation-button--next"></div>
                    </a>
                {% endif %}
            </div>
        </div>

    </div>

</div>

{% endblock %}